### ISSUE TITLE
MRC 실행 오류

### ISSUE THREAD

**Issue by konamgil** [kakaobrain/pororo#16]
## How to reproduce

```python
```

mrc = Pororo(task="mrc", lang="ko")
mrc(
   "카카오브레인이 공개한 것은?",
   "카카오 인공지능(AI) 연구개발 자회사 카카오브레인이 AI 솔루션을 첫 상품화했다. 카카오는 카카오브레인 '포즈(pose·자세분석) API'를 유료 공개한다고 24일 밝혔다. 카카오브레인이 AI 기술을 유료 API를 공개하는 것은 처음이다. 공개하자마자 외부 문의가 쇄도한다. 포즈는 AI 비전(VISION, 영상·화면분석) 분야 중 하나다. 카카오브레인 포즈 API는 이미지나 영상을 분석해 사람 자세를 추출하는 기능을 제공한다."
)

기본 코드 실행시
콘솔 오류로 Segmentation fault: 11 가 보여집니다.

## Environment

- OS : 맥OS Mojave, 10.14.5
- Python version : 3.7.6 
- Misc. :

**Comment by sooftware** [comment]
에러 화면을 달아주실 수 있으실까요?

**Comment by bobae-kim** [comment]
저도 mrc 실행시 맥 OS, python 3.7에서 오류가 납니다.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/bobaekim/virtual_env/kakao/lib/python3.7/site-packages/pororo/tasks/utils/base.py", line 137, in __call__
    return self.predict(sent_a, sent_b, **kwargs)
  File "/Users/bobaekim/virtual_env/kakao/lib/python3.7/site-packages/pororo/tasks/machine_reading_comprehension.py", line 103, in predict
    self._callback(self._tagger, pair_result[0]),
  File "/Users/bobaekim/virtual_env/kakao/lib/python3.7/site-packages/pororo/utils.py", line 39, in postprocess_span
    eojeols.append(tagger.pos(token))
  File "/Users/bobaekim/virtual_env/kakao/lib/python3.7/site-packages/mecab/mecab.py", line 67, in pos
    (surface, feature.pos) for surface, feature in self.parse(sentence)
  File "/Users/bobaekim/virtual_env/kakao/lib/python3.7/site-packages/mecab/mecab.py", line 62, in parse
    for node in lattice
  File "/Users/bobaekim/virtual_env/kakao/lib/python3.7/site-packages/mecab/mecab.py", line 62, in <listcomp>
    for node in lattice
  File "/Users/bobaekim/virtual_env/kakao/lib/python3.7/site-packages/mecab/mecab.py", line 33, in _extract_feature
    assert len(values) == 8
AssertionError

**Comment by Huffon** [comment]
@bobae-kim 
말씀주신 에러는 MeCab에서의 분석 오류로 보입니다.
입력문이 어떻게 됐는지 알려주시겠어요?

**Comment by likejazz** [comment]
GCP에서 AI Platform 인스턴스(Python 3 CUDA Toolkit 11.0)에서 MRC 태스크 실행시 MeCab에서 libiconv 오류가 발생합니다.
<img width="757" alt="Screen Shot 2021-02-04 at 2 01 14 PM" src="https://user-images.githubusercontent.com/1250095/106847032-7752d200-66f1-11eb-84a9-c56e7a2c0d67.png">

**Comment by bobae-kim** [comment]
> @bobae-kim
> 말씀주신 에러는 MeCab에서의 분석 오류로 보입니다.
> 입력문이 어떻게 됐는지 알려주시겠어요?

from pororo import Pororo

mrc = Pororo(task="mrc", lang="ko")

mrc(
   "카카오브레인이 공개한 것은?",
   "카카오 인공지능(AI) 연구개발 자회사 카카오브레인이 AI 솔루션을 첫 상품화했다. 카카오는 카카오브레인 '포즈(pose·자세분석) API'를 유료 공개한다고 24일 밝혔다. 카카오브레인이 AI 기술을 유료 API를 공개하는 것은 처음이다. 공개하자마자 외부 문의가 쇄도한다. 포즈는 AI 비전(VISION, 영상·화면분석) 분야 중 하나다. 카카오브레인 포즈 API는 이미지나 영상을 분석해 사람 자세를 추출하는 기능을 제공한다."
)

실행했을때 
assert len(values) == 8
AssertionError
이 에러가 떴는데요
Pororo의 task에 "mrc" 외에 qa, machine_reading_comprehension등 가능한 task 다 넣어봤는데도 같은 에러가 떴습니다
질문과 문서에 다른 거 넣어도 마찬가지고요.

처음 미캡 설치가 되어 있지 않다고 에러가 나서 에러문에 나오는데로 미캡을 설치 했었고요 (기존에 이미 konlpy, Mecab을 통해서 설치를
한 상태였지만) 
mrc 테스트시 Assertion Error가 계속 뜨는 상태입니다.

감사합니다.

**Comment by likejazz** [comment]
https://github.com/kakaobrain/pororo/issues/16#issuecomment-773029900 이 문제는 `python-mecab-ko` 팩키지의 문제로 보이네요. 여기서 binary 팩키징된 so 파일이 데비안 리눅스 4.19(GCP AI Platform에서 제공하는 최신 버전)에서 동작하지 않는걸로 보이네요. 이 문제는 mecab에서 해결하는 문제이므로 해당 프로젝트에 별도 문의하도록 하겠습니다.

**Comment by bernardscumm** [comment]
@likejazz 
확인해주셔서 감사합니다.
저희도 GCP 환경에서 실험을 해봤는데, GCP AI Platform 의 debian 에서 동일한 오류를 확인할 수 있었습니다.
또한 GCP 의 ubuntu 인스턴스에서는 `python-mecab-ko` 가 설치가 안되는 현상이 있었습니다.

**Comment by Huffon** [comment]
@bobae-kim 
konlpy로 이미 mecab이 설치된 환경에서 `python-mecab-ko`를 재설치하셨다면, 아마 사전 경로가 꼬여있을 가능성이 있을 것 같습니다.
konlpy가 설치되지 않은 새로운 conda 등의 가상환경에서 `pororo` 설치 후 다시 테스트해보시겠어요?

+) `postprocess` 인자를 Optional로 바꾸어 원하는 경우에만 적용이 되도록 수정을 하였습니다.
아래 과정을 통해 실험해보실 수도 있으실 것 같아요.

```console
pip install --upgrade pororo
```

```python
from pororo import Pororo

mrc = Pororo(task="mrc", lang="ko")

mrc(
  "카카오브레인이 공개한 것은?",
  "카카오 인공지능(AI) 연구개발 자회사 카카오브레인이 AI 솔루션을 첫 상품화했다. 카카오는 카카오브레인 '포즈(pose·자세분석) API'를 유료 공개한다고 24일 밝혔다. 카카오브레인이 AI 기술을 유료 API를 공개하는 것은 처음이다. 공개하자마자 외부 문의가 쇄도한다. 포즈는 AI 비전(VISION, 영상·화면분석) 분야 중 하나다. 카카오브레인 포즈 API는 이미지나 영상을 분석해 사람 자세를 추출하는 기능을 제공한다.",
  postprocess=False,
)


```

@likejazz 
네 동일한 환경에서 동일한 에러를 재현하였습니다만, GCP 내 `python-mecab-ko` 지원 이슈인 것으로 확인하였습니다..
`python-mecab-ko`가 여러모로 문제를 많이 일으키고 있는데, 더 나은 방안을 찾아보도록 하겠습니다.
확인해주셔서 감사드립니다 !

**Comment by konamgil** [comment]
@sooftware 
![image](https://user-images.githubusercontent.com/8665406/106977106-01a44000-679d-11eb-9478-7607adf5969d.png)
해당 오류 이미지입니다!

**Comment by konamgil** [comment]
pip install --upgrade pororo
로 업데이트 이후 이슈 해결되었습니다. 감사합니다.

**Comment by bobae-kim** [comment]
> ```python
> "카카오 인공지능(AI) 연구개발 자회사 카카오브레인이 AI 솔루션을 첫 상품화했다. 카카오는 카카오브레인 '포즈(pose·자세분석) API'를 유료 공개한다고 24일 밝혔다. 카카오브레인이 AI 기술을 유료 API를 공개하는 것은 처음이다. 공개하자마자 외부 문의가 쇄도한다. 포즈는 AI 비전(VISION, 영상·화면분석) 분야 중 하나다. 카카오브레인 포즈 API는 이미지나 영상을 분석해 사람 자세를 추출하는 기능을 제공한다."
> ```

안녕하세요. 말씀해주신대로 pororo 업그레이드 후 postprocss=False 실행하니 잘 됩니다.
빠른 피드백에 감사드립니다.

**Comment by bobae-kim** [comment]
> @bobae-kim
> konlpy로 이미 mecab이 설치된 환경에서 `python-mecab-ko`를 재설치하셨다면, 아마 사전 경로가 꼬여있을 가능성이 있을 것 같습니다.
> konlpy가 설치되지 않은 새로운 conda 등의 가상환경에서 `pororo` 설치 후 다시 테스트해보시겠어요?
> 
> +) `postprocess` 인자를 Optional로 바꾸어 원하는 경우에만 적용이 되도록 수정을 하였습니다.
> 아래 과정을 통해 실험해보실 수도 있으실 것 같아요.
> 
> ```
> pip install --upgrade pororo
> ```
> 
> ```python
> from pororo import Pororo
> 
> mrc = Pororo(task="mrc", lang="ko")
> 
> mrc(
>   "카카오브레인이 공개한 것은?",
>   "카카오 인공지능(AI) 연구개발 자회사 카카오브레인이 AI 솔루션을 첫 상품화했다. 카카오는 카카오브레인 '포즈(pose·자세분석) API'를 유료 공개한다고 24일 밝혔다. 카카오브레인이 AI 기술을 유료 API를 공개하는 것은 처음이다. 공개하자마자 외부 문의가 쇄도한다. 포즈는 AI 비전(VISION, 영상·화면분석) 분야 중 하나다. 카카오브레인 포즈 API는 이미지나 영상을 분석해 사람 자세를 추출하는 기능을 제공한다.",
>   postprocess=False,
> )
> ```
> 
> @likejazz
> 네 동일한 환경에서 동일한 에러를 재현하였습니다만, GCP 내 `python-mecab-ko` 지원 이슈인 것으로 확인하였습니다..
> `python-mecab-ko`가 여러모로 문제를 많이 일으키고 있는데, 더 나은 방안을 찾아보도록 하겠습니다.
> 확인해주셔서 감사드립니다 !

안녕하세요
말씀해주신대로 pororo 업그레이드 후 postprocess 값 추가하여 테스트 하니 실행 잘 됩니다.
빠른 피드백에 감사드립니다.

**Comment by sickkal** [comment]
PS C:\python> pip3 install --upgrade pororo
Collecting pororo
  Using cached pororo-0.4.2-py3-none-any.whl (256 kB)
Collecting g2p-en
  Using cached g2p_en-2.1.0-py3-none-any.whl (3.1 MB)
Collecting sentence-transformers>=0.4.1.2
  Using cached sentence-transformers-2.0.0.tar.gz (85 kB)
Collecting fairseq>=0.10.2
  Using cached fairseq-0.10.2.tar.gz (938 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\qusdb\anaconda3\python.exe' 'C:\Users\qusdb\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\qusdb\AppData\Local\Temp\tmp1cry90ip'
       cwd: C:\Users\qusdb\AppData\Local\Temp\pip-install-e5pd6eyp\fairseq_b092c62b5f824cb395520b5e2d2fb269
  Complete output (31 lines):
  Traceback (most recent call last):
    File "setup.py", line 214, in <module>
      do_setup(package_data)
    File "setup.py", line 136, in do_setup
      setup(
    File "C:\Users\qusdb\AppData\Local\Temp\pip-build-env-_tc3mzxq\overlay\Lib\site-packages\setuptools\__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "C:\Users\qusdb\AppData\Local\Temp\pip-build-env-_tc3mzxq\overlay\Lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "C:\Users\qusdb\AppData\Local\Temp\pip-build-env-_tc3mzxq\overlay\Lib\site-packages\setuptools\build_meta.py", line 60, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\qusdb\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
      main()
    File "C:\Users\qusdb\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\qusdb\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\qusdb\AppData\Local\Temp\pip-build-env-_tc3mzxq\overlay\Lib\site-packages\setuptools\build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\qusdb\AppData\Local\Temp\pip-build-env-_tc3mzxq\overlay\Lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "C:\Users\qusdb\AppData\Local\Temp\pip-build-env-_tc3mzxq\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 217, in <module>
      os.unlink(fairseq_examples)
  PermissionError: [WinError 5] 액세스가 거부되었습니다: 'fairseq\\examples'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/02/59/1f466d82d64482e2809a167e0067979c23057b3752e668537d5ff24453c9/fairseq-0.10.2.tar.gz#sha256=45b90d8ccc3f5a4623a523fe2d0465f54413d03fd1ec9a9d7af0461148ca1a68 (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: 'C:\Users\qusdb\anaconda3\python.exe' 'C:\Users\qusdb\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\qusdb\AppData\Local\Temp\tmp1cry90ip' Check the logs for full command output.
Collecting pororo
  Using cached pororo-0.4.1-py3-none-any.whl (253 kB)
  Using cached pororo-0.4.0-py3-none-any.whl (253 kB)
  Using cached pororo-0.3.5-py3-none-any.whl (253 kB)
  Using cached pororo-0.3.4-py3-none-any.whl (216 kB)
  Using cached pororo-0.3.3-py3-none-any.whl (215 kB)
  Using cached pororo-0.3.2-py3-none-any.whl (212 kB)
  Using cached pororo-0.3.1-py3-none-any.whl (211 kB)
Collecting sentence-transformers==0.4.1.2
  Using cached sentence-transformers-0.4.1.2.tar.gz (64 kB)
Collecting whoosh
  Using cached Whoosh-2.7.4-py2.py3-none-any.whl (468 kB)
Requirement already satisfied: lxml in c:\users\qusdb\anaconda3\lib\site-packages (from pororo) (4.6.3)
Requirement already satisfied: pillow>=4.1.1 in c:\users\qusdb\anaconda3\lib\site-packages (from 
pororo) (8.3.1)
Requirement already satisfied: torchvision==0.7.0 in c:\users\qusdb\anaconda3\lib\site-packages (from pororo) (0.7.0)
Collecting wget
  Using cached wget-3.2.zip (10 kB)
Collecting word2word
  Using cached word2word-1.0.0-py3-none-any.whl (31 kB)
Collecting marisa-trie
  Using cached marisa_trie-0.7.6-cp38-cp38-win_amd64.whl (148 kB)
Collecting transformers>=4.0.0
  Using cached transformers-4.9.1-py3-none-any.whl (2.6 MB)
Requirement already satisfied: torch==1.6.0 in c:\users\qusdb\anaconda3\lib\site-packages (from pororo) (1.6.0)
ERROR: Cannot install pororo==0.3.1, pororo==0.3.2, pororo==0.3.3, pororo==0.3.4, pororo==0.3.5, 
pororo==0.4.0, pororo==0.4.1 and pororo==0.4.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    pororo 0.4.2 depends on fairseq>=0.10.2
    pororo 0.4.1 depends on fairseq>=0.10.2
    pororo 0.4.0 depends on fairseq>=0.10.2
    pororo 0.3.5 depends on fairseq>=0.10.2
    pororo 0.3.4 depends on fairseq>=0.10.2
    pororo 0.3.3 depends on fairseq>=0.10.2
    pororo 0.3.2 depends on fairseq>=0.10.2
    pororo 0.3.1 depends on fairseq==0.10.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

윈도우10에서 설치해도 똑같고.. 우분투로 설치해도 똑같은데.. 뭐가 문젤까요?

**Comment by hyunwoongko** [comment]
기록을 위해 남겨둡니다. GCP에서는 다음과 같이 하면 python-mecab-ko를 설치할 수 있습니다.

```
cd
mkdir mecab
cd mecab
wget https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.1.tar.gz
tar xvzf mecab-0.996-ko-0.9.1.tar.gz
cd mecab-0.996-ko-0.9.1
./configure
make
make check
sudo make install
cd .. 
wget https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-1.6.1-20140814.tar.gz
tar xvzf mecab-ko-dic-1.6.1-20140814.tar.gz
cd mecab-ko-dic-1.6.1-20140814
./configure
make
sudo make install
sudo ln -s /usr/local/bin/mecab-config /usr/bin/mecab-config
sudo python3 -m pip install python-mecab-ko —upgrade

```
